version: "3.4"

services:
  typr:
    extends:
      file: compose/compose.typr.yml
      service: typr
    depends_on:
      - typr_database

  typr_database:
    extends:
      file: compose/compose.typr.yml
      service: typr_database

  keycloak:
    extends:
      file: compose/compose.keycloak.yml
      service: keycloak
    networks:
      - frontend
      - keycloak_backend
    volumes:
      - keycloak-data:/var/lib/postgresql/data:rw
      - type: bind
        source: ./compose/keycloak/typr.json
        target: /opt/keycloak/data/import/typr.json
        read_only: false
    depends_on:
      - keycloak_database

  keycloak_database:
    extends:
      file: compose/compose.keycloak.yml
      service: keycloak_database
    networks:
      - keycloak_backend

networks:
  frontend:
    driver: bridge
    internal: false
  typr_backend:
    internal: true
  keycloak_backend:
    internal: true

volumes:
  keycloak-data:
  typr-data:
